

name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==2.1.*'
          version: '5.15.2'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          modules: 'qtcharts'
          tools: 'tools_qtcreator,qt.tools.qtcreator'
      - name: Build lz4 lib
        run: |
          cd ${{github.workspace}}/3rdparty/lz4/build/cmake
          cmake -DLZ4_BUNDLED_MODE=ON  .
          make
          cd ${{github.workspace}}/3rdparty/brotli
          cmake -DBUILD_SHARED_LIBS=OFF
          make
          cd ${{github.workspace}}/3rdparty/snappy
          cmake -DHAVE_LIBLZO2=0 -DHAVE_LIBLZ4=0 && make
          cd ${{github.workspace}}/3rdparty/zstd/build/cmake
          cmake ./ && make
